const GET_PROFILE_DETAILS = 'GET_PROFILE_DETAILS'
const GET_PROFILE_DETAILS_SUCCESS = 'GET_PROFILE_DETAILS_SUCCESS'
const GET_PROFILE_DETAILS_FAILURE = 'GET_PROFILE_DETAILS_FAILURE'
const GO_BACK = 'GO_BACK'

export {
	GET_PROFILE_DETAILS,
	GET_PROFILE_DETAILS_SUCCESS,
	GET_PROFILE_DETAILS_FAILURE,
	GO_BACK,
}
